baseURL = ''
languageCode = 'fi-fi'
PublishDir = 'public'
theme = 'ananke'

title = "Altesmi.github.io"
resourceDir = "../resources"

DefaultContentLanguage = "fi"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.fi]
    weight = 1
    contentDir = "content/fi"
  [languages.en]
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "black"
  author = "Olli-Pekka Tikkasalo"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-white"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "mastodon"
url = "https://mastodontti.fi/@altesmi"